from typing import Any

class Experiment:
    def __init__(self, name: str, metadata: Any | None = None) -> None: ...
    @property
    def run_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    def track(self, value: Any, note: str | None = None) -> None: ...

__all__: list[str]
